export const raindrop = require("./raindrop.png")
export const home_icon = require("./home_icon.png")
export const main_img = require("./main-view.png")
export const second_image = require("./second_img.png")
export const ribbon = require("./ribbon.png")